Reset round timer upon instance start
bloxapp/ssv-spec pull request #100
Opened 2022-11-13 10:39 UTC by amir-blox

Added a call for round timeout upon instance start.

2022-11-13 10:57 UTC, alonmuroch requested changes

2022-11-13 10:57 UTC, alonmuroch commented on qbft/instance.go
> +		i.config.GetTimer().TimeoutForRound(FirstRound)
I wonder if this needs to come before the proposer if

2022-11-13 10:57 UTC, alonmuroch commented on qbft/spectest/tests/controller_spectest.go
> +		} else {
what this suppose to test?

2022-11-13 10:57 UTC, alonmuroch commented
rebase and squash

2022-11-13 11:02 UTC, amir-blox commented on qbft/spectest/tests/controller_spectest.go
> +		} else {
That the timer was called upon start

2022-11-14 08:02 UTC, nivBlox commented
@amir-blox no missing the timeout call to function?

2022-11-14 10:09 UTC, amir-blox commented
@nivBlox the instance exposes `UponRoundTimeout()` which we should call from outside of spec.

2022-11-15 06:37 UTC, alonmuroch commented
@amir-blox rebase  and squash

2022-11-16 06:36 UTC, merged