More blame types
bloxapp/ssv-spec pull request #102
Opened 2022-11-14 07:48 UTC by gl-rockx

* add implementation for blame type FailedEcies

* add spec test for blame type FailedEcies

* add implementation for blame type InvalidScaler

* add spec test for blame type invalid scaler

* add implementation for invalid commitment blame

* add spec test for blame type InvalidCommitment

* fix lint issues

* remove redundant code from blame spec test

* fix generate json for frost spec tests

* Fix typo

* Fix blame

* Refactor blame

* BlameMessage has to contain SignedMessage

* Refactor blame

* Linting

* Improve readability

* Fix unhandled error

Co-authored-by: gldeng <realgldeng@gmail.com>

2022-11-15 06:41 UTC, alonmuroch requested changes

2022-11-15 06:41 UTC, alonmuroch commented on qbft/spectest/generate/main.go
> +	if err := os.WriteFile(fullPath, data, 0644); err != nil {
why do we need to change this?

2022-11-15 06:41 UTC, alonmuroch commented on ssv/spectest/generate/main.go
> +	if err := os.WriteFile(fullPath, data, 0644); err != nil {
why change this?

2022-11-15 06:41 UTC, alonmuroch commented on ssv/spectest/run_test.go
> +	byteValue, err := os.ReadFile(path + "/" + fileName)
why change this?

2022-11-15 09:59 UTC, aayush-rockx commented on qbft/spectest/generate/main.go
> +	if err := os.WriteFile(fullPath, data, 0644); err != nil {
```Deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.```
https://pkg.go.dev/io/ioutil

2022-11-20 11:17 UTC, alonmuroch commented
@gl-rockx could you rebase so we can merge?

2022-11-23 07:18 UTC, merged