Missing Check on Quorum for the RoundChange Justification
bloxapp/ssv-spec pull request #207
Opened 2023-05-01 15:21 UTC by GalRogozinski

### Synopsis
The function getRoundChangeJustification in the qbft/prepare.go file does not check that the
set of constructed Prepare messages is of size quorum. This is a deviation from the [QBFT formal
verification code](https://github.com/ConsenSys/qbft-formal-spec-and-verification/blob/1630128e7f5468c08983d08064230422d9337805/dafny/spec/L1/node_auxiliary_functions.dfy#L673).

### Impact
The function returns a set of valid Prepare messages that is attached to a RoundChange message to
justify the round change by the operator. As specified in the QBFT code, the operator needs to check here
the size of the set. Not checking this can lead to sending around a RoundChange message that is not
accepted by the other operators. This in turn can lead to liveness issues, i.e. the honest operators send
around invalid RoundChange messages that are not accepted by other honest operators. Since the
proposer for a higher round requires quorum-many valid RoundChange messages, this can lead to a
state in which the operators do not find consensus and liveness is not reached.

### Fix
Add missing check and spectest

2023-05-01 15:47 UTC, GalRogozinski commented on qbft/spectest/tests/create_message_spectest.go
> +	//TODO rename to value
The rename affects other test
after the PR is accepted I will open issues for the rename and remove the TODO comment

2023-05-02 15:52 UTC, GalRogozinski commented on qbft/spectest/tests/create_message_spectest.go
> +	} else {
fixed

2023-05-02 15:54 UTC, GalRogozinski commented
State Comparison will be added here after a seperate PR will add this ability to `create_message_spectest.go`

2023-05-10 15:14 UTC, alonmuroch requested changes

2023-05-10 15:37 UTC, GalRogozinski commented on qbft/prepare.go
> +		return nil, nil
We simply make sure the justification will be `nil` (later on the code makes it an empty slice IIRC).

It is worth to say that the audit folks admitted (and I agree) that in practice even w.o the check there is no clear attack vector.

Nonetheless, it is a good check to have and it exists in Dafny

2023-05-10 15:39 UTC, GalRogozinski commented on qbft/prepare.go
> +
done

2023-05-23 13:02 UTC, y0sher approved these changes

2023-05-24 07:07 UTC, alonmuroch approved these changes

2023-05-24 08:05 UTC, GalRogozinski commented
@alonmuroch 
> we have some real world scenario to test this out with?
you mean doing tests on a testnet?

And yes I agree with you. Only if we allow nil proposal values (I don't think we do) maybe then the new check can somehow be important.

But better to be danfy-spec compliant and defensive.

2023-05-24 11:46 UTC, merged